### PR TITLE
Bug fix: https URL links #22

### PR DESCRIPTION
**Pull request by RavenDT**
Code cleanup: Replaced tabs with spaces

### CODE REVIEW

**Comment by RavenDT** [comment]
Hold on.  I missed something.

**Comment by RavenDT** [comment]
Amended commit.  Good to go.

**Comment by StormeHawke** [comment]
@RavenDT Just as a heads up, when using git it's best practice not to amend commits once they've been pushed to a public/common repository but rather make a new commit to fix whatever was wrong with the previous one

**Comment by t0cableguy** [comment]
I think you are over complicating the url issue

**Comment by t0cableguy** [comment]
I really think you are over-complicating the https issue, however I have approved your pull.

**Pull request merged**
